# Gitalk 评论系统配置
gitalk:
  enable: true # 是否启用 Gitalk
  clientID: '0v0' # 从 GitHub OAuth App 获取
  clientSecret: 'OwO' # 从 GitHub OAuth App 获取
  repo: 'leak.moe' # 例如：myblog-comments
  owner: 'moeleak' # 例如：yourusername
  admin: ['moeleak'] # 博客管理员的 GitHub 用户名列表，例如：['yourusername']
  id: location.pathname # 页面的唯一标识，建议使用 pathname
  language: zh-CN # 界面语言，可选 'en', 'zh-CN', 'zh-TW' 等
  distractionFreeMode: false # 是否启用无干扰模式（类似全屏编辑）
  # 如果你的博客部署在 GitHub Pages 以外的地方，可能会遇到 CORS 问题
  # 可以考虑部署一个 CORS 代理，然后取消下面的注释并填入代理地址
  proxy: 'https://proxy-gitalk-api.netlify.app/github_access_token'

